spring.application.name=IssueReport_Service
eureka.client.enabled=false
spring.cloud.discovery.enabled=true

spring.config.import=optional:configserver:http://localhost:8888/
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
server.port=8084

resilience4j.circuitbreaker.instances.notificationService.sliding-window-size=10
resilience4j.circuitbreaker.instances.notificationService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.notificationService.wait-duration-in-open-state=10000
resilience4j.circuitbreaker.instances.notificationService.permitted-number-of-calls-in-half-open-state=3

spring.datasource.url=jdbc:postgresql://localhost:5432/issue_reporting_db
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true