spring.application.name=FeedBack_Service

server.port=8086
spring.application.name=feedback-service


eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}