version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: issuereport-db
    environment:
      POSTGRES_DB: issue_reporting_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  issuereport-service:
    build: .
    container_name: issuereport-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/issue_reporting_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=


      # - SPRING_CONFIG_IMPORT=configserver:
      # - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=
volumes:
  postgres-data: